#if 0
	***	hlms_uv_count0	2
	***	hlms_pose	0
	***	texture_bind0	2
	***	hlms_uv_count	1
	***	diffuse_map0_idx	0
	***	uv_diffuse0	0
	***	out_uv_count	1
	***	num_array_textures	0
	***	alpha_test	0
	***	out_uv0_out_uv	0
	***	sampler_unit_slot_start	2
	***	hlms_identity_viewproj	1
	***	diffuse_map0	1
	***	out_uv0_texture_matrix	0
	***	hlms_pose_normals	0
	***	hlms_pose_half	0
	***	hlms_alphablend	1
	***	num_textures	1
	***	hlms_shadow_uses_depth_texture	0
	***	hlms_tangent	0
	***	hlms_bones_per_vertex	0
	***	out_uv0_tex_unit	0
	***	alpha_test_shadow_caster_only	0
	***	materials_per_buffer	2
	***	hlms_skeleton	0
	***	out_uv0_source_uv	0
	***	diffuse_map	1
	***	hlms_render_depth_only	0
	***	hlms_qtangent	0
	***	out_uv_half_count0	2
	***	diffuse	0
	***	out_uv_half_count	1
	***	diffuse_map0_sampler	0
	***	hlms_normal	0
	***	num_samplers	1
	***	hlms_colour	1
	DONE DUMPING PROPERTIES
	DONE DUMPING PIECES
#endif
